config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :installs
  devise_for :users
  resources :events do
    get :details, on: :member
    get :chat, on: :member
    get :organisation, on: :member
    get :addmovie, on: :member
    get :login_success, on: :member
    get :invite, on: :member
  end

  resources :movie_suggestions do
    member do
      put 'upvote', to: 'movie_suggestions#upvote'
      put 'downvote', to: 'movie_suggestions#downvote'
    end
  end

  root to: 'events#index'
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  def to_param
    auth_token
  end

  has_secure_token :auth_token

  belongs_to :user
  has_and_belongs_to_many :users
  has_many :movie_suggestions
  has_many :movies, through: :movie_suggestions
end

app/controllers/events_controller.rb
# frozen_string_literal: true

# Controller handling everything regarding events
# Contains index/show/new/edit/create/update/destroy/set_event/event_params/invite/details/organisation/addmovie
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy chat details organisation upvote invite addmovie]

  # GET /events or /events.json
  def index
    @all_events = Event.all

    @events = []

    @all_events.each do |event|
      next unless user_signed_in?

      @count = Event.find(event.id).users.all.where(id: current_user.id).count
      @creator = Event.find(event.id).user_id

      @events.push(event) if @count != 0 || @creator === current_user.id
    end
  end

  # GET /events/1 or /events/1.json
  def show
    # @the_event = Event.where(auth_token: params[:auth_token])
    @movie_suggestions = @event.movie_suggestions.order('cached_weighted_score DESC')
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        puts 'Saved'
        format.html { redirect_to login_success_event_path(@event), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        puts 'Wrong Params'
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find_by!(auth_token: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:date, :time, :adress, :user_id)
  end

  def invite
    unless params[:access].nil?
      @count = Event.find(@event.id).users.all.where(id: current_user.id).count

      if @count === 0
        user = User.find(current_user.id)
        @event.users.push(user)
        redirect_to @event
      end
    end
  end

  def details
    @movie_suggestions = @event.movie_suggestions.order('cached_weighted_score DESC')
  end

  def organisation
    @owner = @event.user
    @participants = @event.users
  end

  def addmovie
    @base_url = 'http://omdbapi.com/?'
    @api_partial_url = "apikey=#{ENV['OMDB_API_KEY']}"

    unless params[:search].nil?

      @search = URI.escape(params[:search])

      request = HTTP.get(@base_url + @api_partial_url + "&s=#{@search}&plot=full")
      @request_hash = JSON.parse(request)

    end

    unless params[:movie].nil?

      # Get the movie with the imdbID
      @search = params[:movie]

      @the_movie = JSON.parse(HTTP.get(@base_url + @api_partial_url + "&i=#{@search}&plot=full"))

      # If the movie isn't allready in the DB, then create & save the movie
      if Movie.where(title: @the_movie['Title']).empty?
        create_movie(@the_movie)
      else
        add_existing(@the_movie)
      end
    end
  end
end

def create_movie(the_movie)
  movie = Movie.create({ title: the_movie['Title'],
                         year: the_movie['Year'],
                         runtime: the_movie['Runtime'],
                         genre: the_movie['Genre'],
                         director: the_movie['Director'],
                         actors: the_movie['Actors'],
                         plot: the_movie['Plot'],
                         rating: the_movie['Rating'],
                         poster_url: the_movie['Poster'],
                         trailor_url: '' })
  movie.save
  add_to_event(movie)
end

def add_existing(the_movie)
  # if the movie is allready existing ...
  movie = Movie.where(title: the_movie['Title']).first
  # Add and Save the movie only if the MoviSuggestion doesn't exist for the actual event
  if MovieSuggestion.where(movie_id: movie.id, event_id: @event.id).empty?
    add_to_event(movie)
  else
    redirect_to @event, notice: 'Der Film ist bereits hinzugefügt geworden'
  end
end

def add_to_event(movie)
  ms = MovieSuggestion.create(movie_id: movie.id, event_id: @event.id)
  ms.save
  redirect_to @event, success: 'Film hinzugefügt!'
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/addmovie.html.erb
<%= form_with url: addmovie_event_path(), method: :get, local: true do |f| %>
    <%= f.label :search, "Filmsuche - ENTER zum Bestätigen"%>
    <%= f.text_field :search %>
<% end %>

<% @request_hash %>

<% if !@request_hash.nil? %>
    <%= form_with url: addmovie_event_path(), method: :get, local: true do |f| %>
            <% @request_hash["Search"]&.each do |movie| %>

        <div class="addmovie_field">

            <%= f.radio_button :movie, movie["imdbID"]%>
            <%= f.label :movie, id: movie["imdbID"], :for => "movie_#{movie["imdbID"]}", onclick: "MarkSelection(#{movie["imdbID"]});" do %>
                <img src="<%= movie["Poster"] %>" alt="Poster"/>
                <span>
                <h3> <%= movie["Title"] %> </h3>
                <p><%= movie["Year"] %> </p>
                <span>
            <% end %>
        </div>

            <% end %>
            <%= f.submit "Add Movie", :class=>"bottom_nav bottom_nav--add"%>
    <% end %>
<% end %>

<% if !@the_movie.nil? %>
<%= @the_movie %>
<% end %>

<script>
    function MarkSelection(imdbId){
            console.log(imdbId)

            const labels = document.querySelectorAll("label")

            for(let label of labels){
                label.style.border = "none";
            }

            
            imdbId.style.borderBottomStyle= "solid";
            imdbId.style.borderBottomColor= "white";
            imdbId.style.borderBottomWidth="thick";

            imdbId.style.borderTopStyle= "solid";
            imdbId.style.borderTopColor= "white";
            imdbId.style.borderTopWidth="thick";

    }
</script>

app/views/events/chat.html.erb
<p>
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.   
</p>
<nav class="bottom_nav">
    <%= link_to event_path(), :class=>"bottom_nav__link" do%>
        <i class="material-icons bottom_nav__icon">assessment</i>
        <span class="bottom_nav__text bottom_nav__text--active">Ranking</span>
    <%end%>
    <%= link_to details_event_path(), :class=>"bottom_nav__link" do%>
        <i class="material-icons">theaters</i>
        <span class="bottom_nav__text">Details</span>
    <%end%>
    <%= link_to organisation_event_path(), :class=>"bottom_nav__link" do%>   
        <i class="material-icons">assignment</i>
        <span class="bottom_nav__text">Organisation</span>
    <%end%>
</nav>

app/views/events/details.html.erb
<section class="main">

<%= link_to addmovie_event_path() do%>
    <div class="add_movie"><i class="material-icons">add</i> <p>Add Movie</p></div>
<% end %>



    <div class="detail_list">
    <%if @movie_suggestions.present?%>
        <% @movie_suggestions.each_with_index do |suggestion, rank| %>
        <% movie = suggestion.movie%>
            <div class="moviecard" id="<%=rank%>">
                <h3 class="moviecard__rank">Platz <%=rank+1%></h3>
                <div class="moviecard__background">
                    <img class="moviecard__media" src="<%=movie.poster_url%>" alt="<%=movie.title%> poster">
                    <div class="moviecard__content">
                        <p class="moviecard__time"><%=movie.runtime%> min.</p>
                        <h1 class="moviecard__title"><%=movie.title%></h1>
                        <p class="moviecard__data"><%=movie.genre%></p>
                        <p class="moviecard__short_description moviecard__shortdescription--visible"><%=movie.plot%></p> 
                        <div class="moviecard__extended moviecard__extended--invisible">
                            <p class="moviecard__long_description"><%=movie.plot%></p>
                            <p class="moviecard__directors"><%=movie.director%></p>
                            <p class="moviecard__actors"><%=movie.actors%></p>
                        </div>
                        <div class="vote">
                            <%= link_to upvote_movie_suggestion_path(suggestion), method: :put, remote: true do %>
                                <% if current_user.voted_up_on? suggestion %>
                                    <span class="material-icons vote__upvote--active">
                                        thumb_up_off_alt
                                    </span>
                                <% else %>
                                    <span class="material-icons vote__upvote">
                                        thumb_up_off_alt
                                    </span>
                                <% end %>
                            <% end %>
                            <%= link_to  downvote_movie_suggestion_path(suggestion), method: :put, remote: true do%>
                                <% if current_user.voted_down_on? suggestion %>
                                    <span class="material-icons vote__downvote--active">
                                        thumb_down_off_alt
                                    </span>
                                <% else %>
                                    <span class="material-icons vote__downvote">
                                        thumb_down_off_alt
                                    </span>
                                <% end %>
                            <% end %>
                            <p class="vote__number_downvotes"><%= suggestion.weighted_score %></p>
                        </div>
                    </div>
                    <div class="moviecard__folder moviecard__folder--upfolded">AUSKLAPPEN</div>
                </div>
            </div>
        <% end %>
    <%else%>
        <p>No Movies suggested yet</p>
    <% end %>
    </div>



</section>
<nav class="bottom_nav">
    <%= link_to event_path(), :class=>"bottom_nav__link" do%>
        <i class="material-icons bottom_nav__icon">assessment</i>
        <span class="bottom_nav__text bottom_nav__text--active">Ranking</span>
    <%end%>
    <%= link_to details_event_path(), :class=>"bottom_nav__link  bottom_nav__link--active" do%>
        <i class="material-icons">theaters</i>
        <span class="bottom_nav__text">Details</span>
    <%end%>
    <%= link_to organisation_event_path(), :class=>"bottom_nav__link" do%>   
        <i class="material-icons">assignment</i>
        <span class="bottom_nav__text">Organisation</span>
    <%end%>
</nav>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
  <div class="event_container">
    <%if @events.present?%>
    <% @events.each do |event| %>
      <%= link_to event_path(event), :class=>'event__link' do %>
        <div class="event">
          <!-- <div class="event__host">
              <img src="./assets/sgratkx3xj731.png" alt="hostpic">
          </div> -->
          <div class="event__info">
              <h3 class="event__name"><%= event.user.name + " Movienight"%></h3>
              <div class="event__detail">
                  <span class="event__time"> <i class="material-icons"> query_builder </i> <%= event.time %> </span>
                  <span class="event__date"> <i class="material-icons"> event </i> <%= event.date.strftime("%d.%m") %> </span>
              </div>
          </div>
              <i class="big material-icons big">keyboard_arrow_right</i>
        </div>
      <% end %>
    <% end %>
    <%else%>
      <p>
        You arent invited to any MovieNights ye, either add a new one or join one via an invite link
      </p>
    <%end%>
  </div>

<% if user_signed_in? %>
<nav class="bottom_nav bottom_nav--add">
    <%= link_to new_event_path(), :class=>"bottom_nav__link bottom_nav__link--active" do%>    
        <i class="material-icons">playlist_add</i>
        <span class="bottom_nav__text">Add Movie Night</span>
    <%end%>
</nav>
<% else %>
<nav class="bottom_nav bottom_nav--add">
    <a href="#" class="bottom_nav__link bottom_nav__link">  
        <i class="material-icons">playlist_add</i>
        <span class="bottom_nav__text">Login to Add Movie Night</span>
    </a>
</nav>
<% end %>

app/views/events/invite.html.erb
<div class="invite">

    <h2><%= @event.user.name + " Movienight" %></h2>

      <% if user_signed_in? %>
        <h4> Wilkommen, du kannst der MovieNight beitreten </h4>
      <% else %>
            <h4>Um der MovieNight beizutreten, musst du dich zuerst anmelden:</h4>

            <div class="invite__auth">
                <%= link_to 'Register', new_user_registration_path %>
                <%= link_to 'Sign in', new_user_session_path %>
            </div>
      <% end %>


</div>

<% if user_signed_in? %>
<nav class="bottom_nav bottom_nav--add">
    <%= link_to invite_event_path(access: 'true'), :class=>"bottom_nav__link bottom_nav__link--active" do%>    
        <i class="material-icons">playlist_add</i>
        <span class="bottom_nav__text">Der Movie Night beitreten</span>
    <%end%>
</nav>
<% else %>
<nav class="bottom_nav bottom_nav--add">
    <a href="#" class="bottom_nav__link bottom_nav__link">  
        <i class="material-icons">playlist_add</i>
        <span class="bottom_nav__text">Logge dich ein, um der MovieNight beizutreten</span>
    </a>
</nav>
<% end %>

app/views/events/login_success.html.erb
<div class="invite">

    <h2> Glückwunsch! Deine MovieNight wurde erfolgreich erstellt!</h2>

    <h4> Über folgenden Invitation-Link kannst du deine Freunde einladen: </h4>

    <input type="text" class="invite__url" value="https://movienights.projects.multimediatechnology.at/<%= invite_event_path() %>">

    <%= link_to event_path(), :class=>"invite__link" do%>    
        <p>Zum Homescreen</p>
    <%end%>

</div>

app/views/events/new.html.erb
<%= form_for @event do |e| %>
    <div class="field">
        <%= e.label :adress %>
        <%= e.text_field :adress, :required => true %>
    </div>
    <div class="field">
        <%= e.label :date %>
        <%= e.date_field :date, :required => true %>
    </div>
    <div class="field">
        <%= e.label :time %>
        <%= e.time_field :time , :required => true %>
    </div>

    <%= e.hidden_field :user_id, :value => current_user.id%>

    <div>
        <%= e.submit "Create Movie Night", :class=>"bottom_nav bottom_nav--add" %>
    </div>
<% end %>

app/views/events/organisation.html.erb
    <div class="info2">
        <h4> Admin des Events: </h4>
        <p>
            <%= @owner.name %> 
        </p>
        <h4> Datum und Uhrzeit des Events: </h4>
        <p>
            <%=@event.date%>
            <%=@event.time%>
        </p>
        <h4> Ort des Events: </h4>
        <p>
            <%=@event.adress%>
        </p>

        <h4>Teilnehmer:</h4>
        <div class="info__participants">
            <%@participants.each do |p| %>
            <p> <%= p.name %> </p>
            <%end%>
        </div>

        <h4>Einladungs-Link:</h4>

        <input type="text" class="invite__url" value="https://movienights.projects.multimediatechnology.at/<%= invite_event_path() %>">

    </div>

</section>
<nav class="bottom_nav">
    <%= link_to event_path(), :class=>"bottom_nav__link" do%>
        <i class="material-icons bottom_nav__icon">assessment</i>
        <span class="bottom_nav__text bottom_nav__text--active">Ranking</span>
    <%end%>
    <%= link_to details_event_path(), :class=>"bottom_nav__link" do%>
        <i class="material-icons">theaters</i>
        <span class="bottom_nav__text">Details</span>
    <%end%>
    <%= link_to organisation_event_path(), :class=>"bottom_nav__link bottom_nav__link--active" do%>   
        <i class="material-icons">assignment</i>
        <span class="bottom_nav__text">Organisation</span>
    <%end%>
</nav>

app/views/events/show.html.erb
<section class="main">

    <%if @movie_suggestions.present?%>
    <%movie = @movie_suggestions.first.movie%>
    <%puts "============================================================================"%>
    <%puts movie.poster_url%>
    <header class="header" style="background-image: url('<%=movie.poster_url%>')">
    <%else%>
    <header class="header">


    <%end%>
        <div class="info">
            <h1> <%= @event.user.name + " Movienight"%></h1>
            <h2>
                <i class="material-icons">schedule</i>     
                <%= "#{@event.time},#{@event.date}" %>
            </h2>
            <h2>
                <i class="material-icons">room</i>
                <%= @event.adress %>
            </h2>
        </div>
    </header>

<%= link_to addmovie_event_path() do%>
    <div class="add_movie"><i class="material-icons">add</i> <p>Add Movie</p> </div>
<% end %>
    <div class="suggestion_list">
    <%if @movie_suggestions.present?%>
        <% @movie_suggestions.each_with_index do |suggestion, rank| %>
        <% movie = suggestion.movie%>
            <div class="listcard" style="background-image: url('<%=movie.poster_url%>')">
                <%= link_to details_event_path()+"#"+rank.to_s, :class=>"listcard__link" do%> 
                    <%if rank==0 %>
                        <span class="listcard__rank listcard__rank--first">
                    <%else%>
                        <span class="listcard__rank">
                    <%end%>
                            <%=rank+1 %>
                        </span>
                <%end%>
            </div>
        <% end %>
    <%else%>
        <p>No Movies suggested yet</p>
    <%end%>
    </div>
</section>
<nav class="bottom_nav">
    <%= link_to event_path(), :class=>"bottom_nav__link bottom_nav__link--active" do%>
        <i class="material-icons bottom_nav__icon">assessment</i>
        <span class="bottom_nav__text bottom_nav__text--active">Ranking</span>
    <%end%>
    <%= link_to details_event_path(), :class=>"bottom_nav__link" do%>
        <i class="material-icons">theaters</i>
        <span class="bottom_nav__text">Details</span>
    <%end%>
    <%= link_to organisation_event_path(), :class=>"bottom_nav__link" do%>    
        <i class="material-icons">assignment</i>
        <span class="bottom_nav__text">Organisation</span>
    <%end%>
</nav>